VIVOMEDIA:
  FontAwesome:
    Icon:
      licence: free #pro
      version: 5.12.1
      styles: # enable or disable styles
        solid: true
        light: true
        regular: true
        brands: true
        duotone: false

Neos:
  Neos:
    fusion:
      autoInclude:
        VIVOMEDIA.FontAwesome.Icon: true
    userInterface:
      translation:
        autoInclude:
          VIVOMEDIA.FontAwesome.Icon:
            - 'NodeTypes/*'
