VIVOMEDIA:
  FontAwesome:
    Icon:
      licence: free #pro
      version: 5.12.1

Neos:
  Neos:
    fusion:
      autoInclude:
        VIVOMEDIA.FontAwesome.Icon: true
    userInterface:
      translation:
        autoInclude:
          VIVOMEDIA.FontAwesome.Icon:
            - 'NodeTypes/*'
